spring:
  application:
    name: backend
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-ada-002
    vectorstore:
      mongodb:
        collection-name: embedded_movies
        index-name: vector_index
        path-name: plot_embedding
        initialize-schema: false
  mongodb:
    uri: mongodb+srv://michaeldang0104_db_user:m9tiK5rbFOYbMuGN@mongodb-hackathon.yxj8jm9.mongodb.net/sample_mflix?appName=MongoDB-Hackathon
